name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test tool cache
      run: |
        ls -la $RUNNER_TOOL_CACHE/Python/
        echo $PATH
        ls -la $RUNNER_TOOL_CACHE/Python/3.8.2/
        find $RUNNER_TOOL_CACHE/Python/3.8.2/

    # - name: Set up Python
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install tox

    - name: Run tests
      run: python3 -m tox
